use_frameworks!

def shared_iOS_pods
    platform :ios, '10.0'
    pod 'SwiftyDropbox', :path => '../'
end

def shared_macOS_pods
    platform :osx, '10.12'
    pod 'SwiftyDropbox', :path => '../'
end

target "TestSwiftyDropbox_iOS" do
    shared_iOS_pods
end

target "TestSwiftyDropbox_iOSTests" do
    shared_iOS_pods
end

target "TestSwiftyDropbox_macOS" do
    shared_macOS_pods
end

target "TestSwiftyDropbox_macOSTests" do
    shared_macOS_pods
end