///
/// Auto-generated by Stone, do not modify.
///

import Foundation

/// Datatypes and serializers for the auth namespace
public class Auth {
    /// Errors occurred during authentication.
    public enum AuthError: CustomStringConvertible {
        /// The access token is invalid.
        case InvalidAccessToken
        /// The user specified in 'Dropbox-API-Select-User' is no longer on the team.
        case InvalidSelectUser
        /// The user specified in 'Dropbox-API-Select-Admin' is not a Dropbox Business team admin.
        case InvalidSelectAdmin
        /// An unspecified error.
        case Other

        public var description: String {
            return "\(SerializeUtil.prepareJSONForSerialization(AuthErrorSerializer().serialize(self)))"
        }
    }
    public class AuthErrorSerializer: JSONSerializer {
        public init() { }
        public func serialize(value: AuthError) -> JSON {
            switch value {
                case .InvalidAccessToken:
                    var d = [String: JSON]()
                    d[".tag"] = .Str("invalid_access_token")
                    return .Dictionary(d)
                case .InvalidSelectUser:
                    var d = [String: JSON]()
                    d[".tag"] = .Str("invalid_select_user")
                    return .Dictionary(d)
                case .InvalidSelectAdmin:
                    var d = [String: JSON]()
                    d[".tag"] = .Str("invalid_select_admin")
                    return .Dictionary(d)
                case .Other:
                    var d = [String: JSON]()
                    d[".tag"] = .Str("other")
                    return .Dictionary(d)
            }
        }
        public func deserialize(json: JSON) -> AuthError {
            switch json {
                case .Dictionary(let d):
                    let tag = Serialization.getTag(d)
                    switch tag {
                        case "invalid_access_token":
                            return AuthError.InvalidAccessToken
                        case "invalid_select_user":
                            return AuthError.InvalidSelectUser
                        case "invalid_select_admin":
                            return AuthError.InvalidSelectAdmin
                        case "other":
                            return AuthError.Other
                        default:
                            return AuthError.Other
                    }
                default:
                    fatalError("Failed to deserialize")
            }
        }
    }


    /// Stone Route Objects

    static let tokenRevoke = Route(
        name: "token/revoke",
        namespace: "auth",
        deprecated: false,
        argSerializer: Serialization._VoidSerializer,
        responseSerializer: Serialization._VoidSerializer,
        errorSerializer: Serialization._VoidSerializer,
        attrs: ["host": "api",
                "style": "rpc"]
    )
}
