///
/// Auto-generated by Stone, do not modify.
///

import Foundation

import Alamofire

public class DropboxBase {
    /// Routes within the auth namespace. See AuthRoutes for details.
    public var auth: AuthRoutes!
    /// Routes within the files namespace. See FilesRoutes for details.
    public var files: FilesRoutes!
    /// Routes within the sharing namespace. See SharingRoutes for details.
    public var sharing: SharingRoutes!
    /// Routes within the users namespace. See UsersRoutes for details.
    public var users: UsersRoutes!

    public init(client: DropboxTransportClient) {
        self.auth = AuthRoutes(client: client)
        self.files = FilesRoutes(client: client)
        self.sharing = SharingRoutes(client: client)
        self.users = UsersRoutes(client: client)
    }
}
