
/* Autogenerated. Do not edit. */

import Foundation
/**
    Datatypes and serializers for the team namespace
*/
public class Team {
    /**
        Information about a group.
    */
    public class GroupSummary: CustomStringConvertible {
        /// Undocumented
        public let groupName : String
        /// Undocumented
        public let groupId : String
        /// External ID of group. This is an arbitrary ID that an admin can attach to a group.
        public let groupExternalId : String?
        /// The number of members in the group.
        public let memberCount : UInt32
        public init(groupName: String, groupId: String, memberCount: UInt32, groupExternalId: String? = nil) {
            stringValidator()(value: groupName)
            self.groupName = groupName
            stringValidator()(value: groupId)
            self.groupId = groupId
            nullableValidator(stringValidator())(value: groupExternalId)
            self.groupExternalId = groupExternalId
            comparableValidator()(value: memberCount)
            self.memberCount = memberCount
        }
        public var description : String {
            return "\(SerializeUtil.prepareJSONForSerialization(GroupSummarySerializer().serialize(self)))"
        }
    }
    public class GroupSummarySerializer: JSONSerializer {
        public init() { }
        public func serialize(value: GroupSummary) -> JSON {
            let output = [ 
            "group_name": Serialization._StringSerializer.serialize(value.groupName),
            "group_id": Serialization._StringSerializer.serialize(value.groupId),
            "member_count": Serialization._UInt32Serializer.serialize(value.memberCount),
            "group_external_id": NullableSerializer(Serialization._StringSerializer).serialize(value.groupExternalId),
            ]
            return .Dictionary(output)
        }
        public func deserialize(json: JSON) -> GroupSummary {
            switch json {
                case .Dictionary(let dict):
                    let groupName = Serialization._StringSerializer.deserialize(dict["group_name"] ?? .Null)
                    let groupId = Serialization._StringSerializer.deserialize(dict["group_id"] ?? .Null)
                    let memberCount = Serialization._UInt32Serializer.deserialize(dict["member_count"] ?? .Null)
                    let groupExternalId = NullableSerializer(Serialization._StringSerializer).deserialize(dict["group_external_id"] ?? .Null)
                    return GroupSummary(groupName: groupName, groupId: groupId, memberCount: memberCount, groupExternalId: groupExternalId)
                default:
                    fatalError("Type error deserializing")
            }
        }
    }
    /**
        The group type determines how a group is created and managed.
    */
    public enum GroupType: CustomStringConvertible {
        /**
            A group to which team members are automatically added. Applicable to team folders
            https://www.dropbox.com/help/986 only.
        */
        case Team
        /**
            A group is created and managed by a user.
        */
        case UserManaged
        case Other
        public var description : String {
            return "\(SerializeUtil.prepareJSONForSerialization(GroupTypeSerializer().serialize(self)))"
        }
    }
    public class GroupTypeSerializer: JSONSerializer {
        public init() { }
        public func serialize(value: GroupType) -> JSON {
            switch value {
                case .Team:
                    var d = [String : JSON]()
                    d[".tag"] = .Str("team")
                    return .Dictionary(d)
                case .UserManaged:
                    var d = [String : JSON]()
                    d[".tag"] = .Str("user_managed")
                    return .Dictionary(d)
                case .Other:
                    var d = [String : JSON]()
                    d[".tag"] = .Str("other")
                    return .Dictionary(d)
            }
        }
        public func deserialize(json: JSON) -> GroupType {
            switch json {
                case .Dictionary(let d):
                    let tag = Serialization.getTag(d)
                    switch tag {
                        case "team":
                            return GroupType.Team
                        case "user_managed":
                            return GroupType.UserManaged
                        case "other":
                            return GroupType.Other
                        default:
                            return GroupType.Other
                    }
                default:
                    fatalError("Failed to deserialize")
            }
        }
    }
}
